/// @description Insert description here
// You can write your code in this editor
event_inherited();
/*
if(keyboard_check(ord("Q"))){testArrayOfArguments("Q");};
if(keyboard_check(ord("W"))){testArrayOfArguments("Q","W");};
if(keyboard_check(ord("E"))){testArrayOfArguments("Q","W","E");};
if(keyboard_check(ord("R"))){testArrayOfArguments("Q","W","E","R");};
if(keyboard_check(ord("T"))){testArrayOfArguments("Q","W","E","R","T");};
if(keyboard_check(ord("Y"))){testArrayOfArguments("Q","W","E","R","T","Y");};
if(keyboard_check(ord("U"))){testArrayOfArguments("Q","W","E","R","T","Y","U");};
if(keyboard_check(ord("I"))){testArrayOfArguments("Q","W","E","R","T","Y","U","I");};
if(keyboard_check(ord("O"))){testArrayOfArguments("Q","W","E","R","T","Y","U","I","O");};
if(keyboard_check(ord("P"))){testArrayOfArguments("Q","W","E","R","T","Y","U","I","O","P");};
*/

///////////////DEBUG PURPOSES ONLY////////////////////
if(keyboard_check(ord("Q"))){
	draw_text(50,50,myPos);
	//testArrayOfArguments("Q");
};
if(keyboard_check(ord("W"))){
	draw_text(50,50,mySpeed);
	//testArrayOfArguments("Q","W");
};
if(keyboard_check(ord("E"))){
	draw_text(50,50,myAccel);
	//testArrayOfArguments("Q","W","E");
};
if(keyboard_check(ord("R"))){
	draw_text(50,50,myHealth);
	//testArrayOfArguments("Q","W","E","R");
};
if(keyboard_check(ord("T"))){
	draw_text(50,50,onTheGround);
	//testArrayOfArguments("Q","W","E","R","T");
};
if(keyboard_check(ord("Y"))){
	draw_text(50,50,myWidth);
	//testArrayOfArguments("Q","W","E","R","T","Y");
};
if(keyboard_check(ord("U"))){
	draw_text(50,50,myHeight);
	//testArrayOfArguments("Q","W","E","R","T","Y","U");
};
if(keyboard_check(ord("I"))){
	//testArrayOfArguments("Q","W","E","R","T","Y","U","I");
};
if(keyboard_check(ord("O"))){
	//testArrayOfArguments("Q","W","E","R","T","Y","U","I","O");
};
if(keyboard_check(ord("P"))){
	//testArrayOfArguments("Q","W","E","R","T","Y","U","I","O","P");
};